version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: automotive_dwh_db
    environment:
      POSTGRES_DB: automotive_dwh
      POSTGRES_USER: automotive
      POSTGRES_PASSWORD: automotive
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
